name: Test code on pull request

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Code Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            .next/cache
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Delete node_modules and .next cache
        run: rm -rf node_modules .next/cache

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript
        run: npm run type-check --if-present

      - name: Run ESLint
        run: npm run lint

      - name: Build Project
        timeout-minutes: 10
        run: npm run build

      - name: Run Tests
        run: npx jest --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: NewJiSoo/Hoit
